// Generated by gencpp from file aut_sys/distance.msg
// DO NOT EDIT!


#ifndef AUT_SYS_MESSAGE_DISTANCE_H
#define AUT_SYS_MESSAGE_DISTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aut_sys
{
template <class ContainerAllocator>
struct distance_
{
  typedef distance_<ContainerAllocator> Type;

  distance_()
    : distance(0.0)  {
    }
  distance_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::aut_sys::distance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aut_sys::distance_<ContainerAllocator> const> ConstPtr;

}; // struct distance_

typedef ::aut_sys::distance_<std::allocator<void> > distance;

typedef boost::shared_ptr< ::aut_sys::distance > distancePtr;
typedef boost::shared_ptr< ::aut_sys::distance const> distanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aut_sys::distance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aut_sys::distance_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aut_sys::distance_<ContainerAllocator1> & lhs, const ::aut_sys::distance_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aut_sys::distance_<ContainerAllocator1> & lhs, const ::aut_sys::distance_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aut_sys

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::aut_sys::distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aut_sys::distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aut_sys::distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aut_sys::distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aut_sys::distance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aut_sys::distance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aut_sys::distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e77fb10f0c8b4833ec273aa9ac74459";
  }

  static const char* value(const ::aut_sys::distance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e77fb10f0c8b483ULL;
  static const uint64_t static_value2 = 0x3ec273aa9ac74459ULL;
};

template<class ContainerAllocator>
struct DataType< ::aut_sys::distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aut_sys/distance";
  }

  static const char* value(const ::aut_sys::distance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aut_sys::distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 distance\n"
;
  }

  static const char* value(const ::aut_sys::distance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aut_sys::distance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct distance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aut_sys::distance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aut_sys::distance_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUT_SYS_MESSAGE_DISTANCE_H
