// Generated by gencpp from file aut_sys/motors.msg
// DO NOT EDIT!


#ifndef AUT_SYS_MESSAGE_MOTORS_H
#define AUT_SYS_MESSAGE_MOTORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aut_sys
{
template <class ContainerAllocator>
struct motors_
{
  typedef motors_<ContainerAllocator> Type;

  motors_()
    : leftSpeed(0.0)
    , rightSpeed(0.0)  {
    }
  motors_(const ContainerAllocator& _alloc)
    : leftSpeed(0.0)
    , rightSpeed(0.0)  {
  (void)_alloc;
    }



   typedef float _leftSpeed_type;
  _leftSpeed_type leftSpeed;

   typedef float _rightSpeed_type;
  _rightSpeed_type rightSpeed;





  typedef boost::shared_ptr< ::aut_sys::motors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aut_sys::motors_<ContainerAllocator> const> ConstPtr;

}; // struct motors_

typedef ::aut_sys::motors_<std::allocator<void> > motors;

typedef boost::shared_ptr< ::aut_sys::motors > motorsPtr;
typedef boost::shared_ptr< ::aut_sys::motors const> motorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aut_sys::motors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aut_sys::motors_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aut_sys::motors_<ContainerAllocator1> & lhs, const ::aut_sys::motors_<ContainerAllocator2> & rhs)
{
  return lhs.leftSpeed == rhs.leftSpeed &&
    lhs.rightSpeed == rhs.rightSpeed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aut_sys::motors_<ContainerAllocator1> & lhs, const ::aut_sys::motors_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aut_sys

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::aut_sys::motors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aut_sys::motors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aut_sys::motors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aut_sys::motors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aut_sys::motors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aut_sys::motors_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aut_sys::motors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a7e2ab059b1bb7e605831ab6e7ce11f";
  }

  static const char* value(const ::aut_sys::motors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a7e2ab059b1bb7eULL;
  static const uint64_t static_value2 = 0x605831ab6e7ce11fULL;
};

template<class ContainerAllocator>
struct DataType< ::aut_sys::motors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aut_sys/motors";
  }

  static const char* value(const ::aut_sys::motors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aut_sys::motors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 leftSpeed\n"
"float32 rightSpeed\n"
;
  }

  static const char* value(const ::aut_sys::motors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aut_sys::motors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leftSpeed);
      stream.next(m.rightSpeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aut_sys::motors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aut_sys::motors_<ContainerAllocator>& v)
  {
    s << indent << "leftSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.leftSpeed);
    s << indent << "rightSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.rightSpeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUT_SYS_MESSAGE_MOTORS_H
