// Generated by gencpp from file aut_sys/servos.msg
// DO NOT EDIT!


#ifndef AUT_SYS_MESSAGE_SERVOS_H
#define AUT_SYS_MESSAGE_SERVOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aut_sys
{
template <class ContainerAllocator>
struct servos_
{
  typedef servos_<ContainerAllocator> Type;

  servos_()
    : pan(0.0)
    , tilt(0.0)  {
    }
  servos_(const ContainerAllocator& _alloc)
    : pan(0.0)
    , tilt(0.0)  {
  (void)_alloc;
    }



   typedef float _pan_type;
  _pan_type pan;

   typedef float _tilt_type;
  _tilt_type tilt;





  typedef boost::shared_ptr< ::aut_sys::servos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aut_sys::servos_<ContainerAllocator> const> ConstPtr;

}; // struct servos_

typedef ::aut_sys::servos_<std::allocator<void> > servos;

typedef boost::shared_ptr< ::aut_sys::servos > servosPtr;
typedef boost::shared_ptr< ::aut_sys::servos const> servosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aut_sys::servos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aut_sys::servos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aut_sys::servos_<ContainerAllocator1> & lhs, const ::aut_sys::servos_<ContainerAllocator2> & rhs)
{
  return lhs.pan == rhs.pan &&
    lhs.tilt == rhs.tilt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aut_sys::servos_<ContainerAllocator1> & lhs, const ::aut_sys::servos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aut_sys

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::aut_sys::servos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aut_sys::servos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aut_sys::servos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aut_sys::servos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aut_sys::servos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aut_sys::servos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aut_sys::servos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "938e11f380abc0513a5b7367d0f157bf";
  }

  static const char* value(const ::aut_sys::servos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x938e11f380abc051ULL;
  static const uint64_t static_value2 = 0x3a5b7367d0f157bfULL;
};

template<class ContainerAllocator>
struct DataType< ::aut_sys::servos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aut_sys/servos";
  }

  static const char* value(const ::aut_sys::servos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aut_sys::servos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pan\n"
"float32 tilt\n"
;
  }

  static const char* value(const ::aut_sys::servos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aut_sys::servos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pan);
      stream.next(m.tilt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct servos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aut_sys::servos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aut_sys::servos_<ContainerAllocator>& v)
  {
    s << indent << "pan: ";
    Printer<float>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<float>::stream(s, indent + "  ", v.tilt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUT_SYS_MESSAGE_SERVOS_H
